[package]
name = "syscoin_client"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoincore-rpc = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.11", features = ["json"] }
hex = "0.4"
tokio = { version = "1", features = ["full"] }